# Generated by Django 4.2.7 on 2023-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='baterai_mAh',
        ),
        migrations.AddField(
            model_name='laptop',
            name='baterai',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='nilai_saw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='harga',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='layar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memori_internal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
