# Generated by Django 4.2.7 on 2023-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_laptop_baterai_mah_laptop_baterai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='baterai',
            field=models.FloatField(default=0.0),
        ),
    ]
