# Generated by Django 4.2.7 on 2023-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_laptop_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='baterai',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='harga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='layar',
            field=models.IntegerField(),
        ),
    ]
