# Generated by Django 4.2.7 on 2023-11-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_laptop_baterai_alter_laptop_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='layar',
            field=models.FloatField(),
        ),
    ]
