# Generated by Django 4.2.7 on 2023-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_laptop_layar'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='norm_baterai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='norm_harga',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='norm_layar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='norm_memori_internal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='norm_ram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
